void Timer0_Init();
void Timer1_Init();
#include "TimerInit.c"
void T1_delay(int);
void T0_delay(int);
void PORTA_Init_Output(uint8_t);
void PORTC_Init_Output(uint8_t);
void PORTD_Init_Output(uint8_t);
void delay(double);
void PortF_Button_Handle(void);
void PORTF_Interrupt_Init(void);
void PortB_Button_Handle(void);
void PORTB_Interrupt_Init(void);
void UART0_init(void);
#include "myUART.c"
#include "PortInit.c"
#include "ButtonInt.c"
